### ISSUE TITLE
Question:  Example of capturing combination keys

### ISSUE THREAD

**Issue by tmosson1** [0x2E757/InputInterceptor#1]
I was wondering if you had an example on how you can capture key combinations using this. (i.e. Ctrl-A). I couldn't find one in the example or if it is there I apologize I must of overlooked it.

**Comment by 0x2E757** [comment]
The driver this library is based on doesn't support such functionality, as far as I remember. The simplest solution is to use boolean flags for each button of the combination and check if all of them are still pressed after any of then was pressed. Obviously, if you want lot of combinations to be supported, your code is going to be messy. In that case you can write some proxy class which will store information about pressed buttons inside itself, and the only thing you will need to do is to pipe interceptor callbacks to that class, as well as implement subscriber function that will accept list of buttons required to be presssed and callback.

**Comment by EjiHuang** [comment]
Maybe like this
```CSharp
bool isAltDown = false;
// hook
keyboardHook = new KeyboardHook((ref KeyStroke key) =>
{
    if (key.Code == KeyCode.J && key.State == KeyState.Down)
    {
        if (isAltDown == true)
        {
            SetStatusInfo(Status_Flag.info, $"alt + f hook.");
        }
    }
    if (key.Code == KeyCode.Alt && key.State == KeyState.Down)
    {
        isAltDown = true;
    }
    else if (key.Code == KeyCode.Alt && key.State == KeyState.Up)
    {
        isAltDown = false;
    }
});
```

**Comment by 0x2E757** [comment]
This will work and will be more clean with lot of combinations:
```C#
Boolean isCtrlDown = false;
Boolean isADown = false;
KeyboardHook keyboardHook = new KeyboardHook((ref KeyStroke key) => {
    if (key.State == KeyState.Down) {
        if (key.Code == KeyCode.Control || key.Code == KeyCode.A) {
            if (isCtrlDown && isADown)
                // Both buttons are pressed now
        }
    }
    switch (key.Code) {
        case (KeyCode.Control):
            isCtrlDown = key.State == KeyState.Down;
            break;
        case (KeyCode.A):
            isADown = key.State == KeyState.Down;
            break;
    }
});
```

**Comment by Lildtz** [comment]
Is possible use like "shift + A" in SimulateKeyPress?

**Comment by 0x2E757** [comment]
> Is possible use like "shift + A" in SimulateKeyPress?

Simultaneously pressed buttons can be simulated only this way:
```C#
KeyboardHook.SetKeyState(KeyCode.LeftShift, KeyState.Down);
KeyboardHook.SetKeyState(KeyCode.A, KeyState.Down);
KeyboardHook.SetKeyState(KeyCode.A, KeyState.Up);
KeyboardHook.SetKeyState(KeyCode.LeftShift, KeyState.Up);
```
or a bit easier
```C#
KeyboardHook.SetKeyState(KeyCode.LeftShift, KeyState.Down);
KeyboardHook.SimulateKeyPress(KeyCode.A);
KeyboardHook.SetKeyState(KeyCode.LeftShift, KeyState.Up);
```

Second variant should be more preferred as it includes delay before button released.
