### ISSUE TITLE
Not intercepting the initial down press

### ISSUE THREAD

**Issue by YoloXDAim** [0x2E757/InputInterceptor#10]
Hi, I made a app that converts mouse and keyboard to virtual controller, when i press wasd it first shows native input then when i hold it long it will change to joystick, how can i make it intercept from the initial down.

**Comment by 0x2E757** [comment]
Sorry for late response, probably you're doing something wrong but I can't help more without example of your code.

**Comment by YoloXDAim** [comment]
Ill send you snippit in couple hours

**Comment by YoloXDAim** [comment]
ITs still sending the initil mouse press without intercepting it and only debuging.
private void MouseCallback(ref MouseStroke mouseStroke)
{
   
    if (mouseStroke.State == MouseState.LeftButtonDown)
    {
        Debug.WritLine("LeftDown");
    }
    else
    {
        Debug.WritLine("LeftUp");
    }


    if (mouseStroke.State == MouseState.RightButtonDown)
    {
          Debug.WritLine("RightDown");
    }
    else
    {
        Debug.WritLine("RightUp");
    }
    }

**Comment by 0x2E757** [comment]
You can't use `if else` like that to distinguish keys/actions when working with input. This is so much basics that I'm not going to explain it further, ChatGPT is free, use him.
