### ISSUE TITLE
Uninstall driver

### ISSUE THREAD

**Issue by goatandsheep** [0x2E757/InputInterceptor#2]
Is there a way to uninstall the driver programmatically?

**Comment by 0x2E757** [comment]
Hello. No, such method isn't implemented. I'm not sure if you can do so for this library as installed NuGet package, but it should be easy by making fork and creating copy of `InstallDriver`with `uninstall` argument in `InputInterceptor.cs`. You also might make a PR and I'll update NuGet package later.
