### ISSUE TITLE
Resource name wrong match.

### ISSUE THREAD

**Issue by chenijih2017** [0x2E757/InputInterceptor#6]
In the ExecuteInstaller function of InputInterceptor.cs, there is one line:
`
Helpers.GetResource("install_interception.exe"));
`

It should be changed to:
`
Helpers.GetResource("install-interception.exe"));
`

**Comment by 0x2E757** [comment]
Fixed. Many thanks for reporting, couldn't notice this as I had installed driver using older library versions.
