### ISSUE TITLE
Incorrect type on HardwareId

### ISSUE THREAD

**Issue by MaverickMartyn** [0x2E757/InputInterceptor#7]
The hardware id returned in DeviceData from GetDeviceList() is returned as a string.
This is supposed to be a string array.
If multiple values are retrieved, the returned string will contain a bunch of `\0` escape characters denoting the end of each element in the array.

Otherwise this is working great for my application. :)
Fixing this would aid in making it easier to retrieve human readable device names from WMI.
Better yet, if it is available to you maybe you could return a more descriptive object, containing more info about the device?

**Comment by 0x2E757** [comment]
This library is kinda meant to be just a wrapper for the driver, though changes you proposed weren't hard to implement so I've updated DeviceData class and now it contains initial string (but wiln't contain \0 chars anymore) and splitted array.
